<?php /** @var \OuterEdge\Base\Block\Html\Notices $block */ ?>
<?php if ($block->hasErrors()): ?>
    <div class="message global edge" id="notice-edge-block" style="position: absolute; background-color: rgba(204, 204, 204, 0.37);">
        <div class="content" style="font-size: 9px;">
            <?php foreach ($block->getErrorMessages() as $error) : ?>
                <?= $error; ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
