<?php
$termlyCookiePolicyDataId = str_replace('https://app.termly.io/document/cookie-policy/', '', $this->helper('OuterEdge\Base\Helper\Config')->getConfig('oe_base/cmp/termly_cookie_policy'));
?>

<div name="termly-embed" data-id="<?= $termlyCookiePolicyDataId ?>"></div>
<script type="text/javascript">(function(d, s, id) {
  var js, tjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "https://app.termly.io/embed-policy.min.js";
  tjs.parentNode.insertBefore(js, tjs);
}(document, 'script', 'termly-jssdk'));</script>
