<a class="link-copyright" href="http://magento.com" target="_blank" title="<?php /* @escapeNotVerified */ echo __('Magento') ?>"></a>
<?php /* @escapeNotVerified */ echo __('Copyright&copy; %1 Magento Commerce Inc. All rights reserved.', date('Y')) ?>
<br>
<a href="http://outeredgeuk.com/" target="_blank" title="<?php /* @escapeNotVerified */ echo __('Outeredge') ?>">
    <img src="<?php echo $block->getViewFileUrl('Edge_Base::images/logo-outeredge.png')?>">
</a>